services:
  - type: web
    name: radar
    env: python
    plan: free
    buildCommand: "pip install -r radar_bot/requirements.txt"
    startCommand: "python -m radar_bot.app.main"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BACKEND_URL
        sync: false
